# Generated by Django 4.1.5 on 2023-01-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('systemic_name', models.CharField(max_length=250, unique=True, verbose_name='Системное название')),
            ],
            options={
                'verbose_name': 'Категория Меню',
                'verbose_name_plural': 'Категории Меню',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка на раздел меню')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='tree_menu.menucategories', verbose_name='Категория')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree_menu.menu', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['name'],
            },
        ),
    ]
